config/routes.rb
Rails.application.routes.draw do
  get "whereyat" => "map#where"
  get "riderprofile" => "riders#index"

  resources :riders
  devise_for :users

  root "riders#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rider.rb
class Rider < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :riders
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:first, :last, :checkin, :longitude, :latitude, :timestamp])
	devise_parameter_sanitizer.permit(:sign_up, keys: [:first, :last, :checkin, :longitude, :latitude, :timestamp])
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def where
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /riders
  # GET /riders.json
  def index
    @riders = Rider.all
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
  end

  # GET /riders/new
  def new
    @rider = Rider.new
  end

  # GET /riders/1/edit
  def edit
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = Rider.new(rider_params)

    respond_to do |format|
      if @rider.save
        format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
        format.json { render :show, status: :created, location: @rider }
      else
        format.html { render :new }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riders/1
  # PATCH/PUT /riders/1.json
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url, notice: 'Rider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = Rider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.require(:rider).permit(:parade, :float, :side, :level, :position, :userid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mardigrasme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Rider Profile", new_rider_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
	<div class="container">
      <%= yield %>
    </div>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB0fYj6TCYXPSp6NMdHhYp0ObjA3BP4b4s&callback=initMap">
</script>

</body>
</html>

app/views/map/where.html.erb
    <div id="map"></div>
 

app/views/riders/_form.html.erb
<%= form_with(model: rider, local: true) do |form| %>
  <% if rider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rider.errors.count, "error") %> prohibited this rider from being saved:</h2>

      <ul>
      <% rider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :parade %>
    <%= form.text_field :parade, id: :rider_parade %>
  </div>

  <div class="field">
    <%= form.label :float %>
    <%= form.text_field :float, id: :rider_float %>
  </div>

  <div class="field">
    <%= form.label :side %>
    <%= form.text_field :side, id: :rider_side %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :rider_level %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position, id: :rider_position %>
  </div>

  <div class="field">
    <%= form.label :userid %>
    <%= form.number_field :userid, id: :rider_userid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/riders/edit.html.erb
<h1>Editing Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Show', @rider %> |
<%= link_to 'Back', riders_path %>

app/views/riders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Riders</h1>

<table>
  <thead>
    <tr>
      <th>Parade</th>
      <th>Float</th>
      <th>Side</th>
      <th>Level</th>
      <th>Position</th>
      <th>Userid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @riders.each do |rider| %>
      <tr>
        <td><%= rider.parade %></td>
        <td><%= rider.float %></td>
        <td><%= rider.side %></td>
        <td><%= rider.level %></td>
        <td><%= rider.position %></td>
        <td><%= rider.userid %></td>
        <td><%= link_to 'Show', rider %></td>
        <td><%= link_to 'Edit', edit_rider_path(rider) %></td>
        <td><%= link_to 'Destroy', rider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rider', new_rider_path %>

app/views/riders/new.html.erb
<h1>New Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Back', riders_path %>

app/views/riders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parade:</strong>
  <%= @rider.parade %>
</p>

<p>
  <strong>Float:</strong>
  <%= @rider.float %>
</p>

<p>
  <strong>Side:</strong>
  <%= @rider.side %>
</p>

<p>
  <strong>Level:</strong>
  <%= @rider.level %>
</p>

<p>
  <strong>Position:</strong>
  <%= @rider.position %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @rider.userid %>
</p>

<%= link_to 'Edit', edit_rider_path(@rider) %> |
<%= link_to 'Back', riders_path %>